### ISSUE TITLE
Review README wording

### ISSUE THREAD

**Issue by tieganh** [OpenDRR/earthquake-scenarios#1]
Check that the readme covers the necessary topics (introduce the material, point people where they need to go, answer questions someone would have, liability, etc) with appropriate wording.

**Comment by plesueur** [comment]
[Scenario Catalogue_readme_PL.docx](https://github.com/OpenDRR/earthquake-scenarios/files/6592894/Scenario.Catalogue_readme_PL.docx)
Hi @tieganh, I took a look at the README wording, and have provided comments/edits in the attached .docx. Let me know if you have any questions.

**Comment by tieganh** [comment]
Updated the README based on @plesueur's comments in [this commit](https://github.com/OpenDRR/earthquake-scenarios/commit/c1952321a4d2ea228d179dbeff9c0111a2240575), and have included Malaika's feedback via email. Considering this an acceptable level of review - thanks everyone!
