### ISSUE TITLE
Generate geopackage files for scenarios in finished directory

### ISSUE THREAD

**Issue by DamonU2** [OpenDRR/earthquake-scenarios#14]
Auto or manually generate geopackage files for completed scenarios

**Comment by DamonU2** [comment]
@wkhchow Would it be possible to generate a file for a single scenario so that I can work on some tests?

**Comment by DamonU2** [comment]
@wkhchow Don't worry about it, apparently I can just get what I need from the API.

**Comment by wkhchow** [comment]
@DamonU2 Okay, but let me know and I can generate a newer gpkg if needed (with latest updates).

**Comment by jvanulde** [comment]
> @DamonU2 Okay, but let me know and I can generate a newer gpkg if needed (with latest updates).

@wkhchow we'll need them anyways so generate them when you have time. No rush.

**Comment by jvanulde** [comment]
@wkhchow let's add this Sprint 45 please. @anthonyfok we need to enable the Action to push the zipped GPKG files to release assets. @DamonU2 make sure your links point to release assets in the data repo. Thanks guys.

**Comment by DamonU2** [comment]
GPKG's added to repo, and to release assets
