### ISSUE TITLE
Create metadata records in FGP

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/earthquake-scenarios#29]
Add collection metadata and records for each scenario.

**Comment by jvanulde** [comment]
Records are in draft undergoing review.

**Comment by jvanulde** [comment]
Records are complete. We are waiting on the MXD files prior to sending the geopackages to the FGP.

**Comment by jvanulde** [comment]
Still to do:

* [ ] update extents for Val des bois and Georgia Strait records
* [ ] update all thumbnails using @CarolLWagner MXD representation
* [ ] update GPKG links to point to v1.1.0 release assets

**Comment by jvanulde** [comment]
All collections have been added to FGP. We will wait on the official release of RiskProfiler in October before adding the OpenDRR OGC service endpoints.

**Comment by wkhchow** [comment]
Will continue progress as new DSRA scenarios come along
