### ISSUE TITLE
Update scenario overview map 

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/earthquake-scenarios#3]
Update the map showing all available scenarios. May have to switch to cartopy from Basemap.

[Bash Script](https://github.com/OpenDRR/earthquake-scenarios/blob/master/scripts/finishedMap.sh) 
[Python Script](https://github.com/OpenDRR/earthquake-scenarios/blob/master/scripts/finishedMap.py)
Can check out [Take Snapshot Script](https://github.com/OpenDRR/earthquake-scenarios/blob/master/scripts/TakeSnapshot.py) for working example with CartoPy.

**Comment by tieganh** [comment]
Updated links above
