### ISSUE TITLE
r2 to r1 for finished scenario

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/earthquake-scenarios#8]
@tieganh if we check the https://github.com/OpenDRR/earthquake-scenarios/blob/master/FINISHED/SIM9p0_CascadiaInterfaceBestFault.md it shows b0/r1 files but in the finished folder for cascadia interface we see b0/r2.  I think this was from the previous iteration where we did a dirty fix to to run all the scenarios and in my script rename it back to r1.  

Now that we are starting this 'final' repo for scenarios, We should be reverting back to how it was originally planed b0/r1 and we will implement the changes on our end.  So this way it should run fine with all the current and new scenarios that will you will be putting in the repo.  Right now the Cascadia interface best fault scenarios are labeled b0/r2, and the newer leech river ones are b0/r1.

Would you be able to rename the cascadia scenarios back to r1?

**Comment by tieganh** [comment]
Confirmed that this was a naming issue only, and switched 'r2's back to 'r1' in FINISHED.
